apiVersion: ibp.com/v1beta1
kind: IBPCA
metadata:
  name: org0-ca
  namespace: test-network
spec:
  action:
    renew: {}
  configoverride:
    ca:
      affiliations:
        org1:
        - department1
        - department2
        org2:
        - department1
      debug: true
      registry:
        identities:
        - attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: rcaadmin
          pass: rcaadminpw
          type: client
        - name: orderer1
          pass: orderer1pw
          type: orderer
        - name: orderer2
          pass: orderer2pw
          type: orderer
        - name: orderer3
          pass: orderer3pw
          type: orderer
        - name: org0admin
          pass: org0adminpw
          type: admin
      signing:
        default:
          expiry: 87600h0m0s
    tlsca:
      affiliations:
        org0:
        - department1
        org1:
        - department1
        - department2
      debug: true
      registry:
        identities:
        - attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: admin
          pass: adminpw
          type: client
        - name: orderer1
          pass: orderer1pw
          type: orderer
        - name: orderer2
          pass: orderer2pw
          type: orderer
        - name: orderer3
          pass: orderer3pw
          type: orderer
        - name: org0admin
          pass: org0adminpw
          type: admin
      signing:
        default:
          expiry: 87600h0m0s
  customNames:
    pvc: {}
  domain: localho.st
  images:
    caImage: 172.22.50.223/hyperledger/fabric-ca
    caInitImage: 172.22.50.223/hyperledger/ubi-minimal
    caInitTag: latest
    caTag: 1.5.5
  ingress:
    class: ""
    tlsSecretName: ""
  license:
    accept: true
  replicas: 1
  resources:
    ca:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M
    init:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M
  service:
    type: ClusterIP
  storage:
    ca:
      class: openebs-hostpath
      size: 100M
  version: 1.5.5
status:
  lastHeartbeatTime: 2022-11-10 03:51:11.117454486 +0000 UTC m=+1211336.410228586
  reason: allPodsDeployed
  status: "True"
  type: Deployed
  version: 1.0.0
  versions:
    reconciled: 1.5.5